### ISSUE TITLE
Pitch and roll response curve

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#1]
Let me start by saying thanks so much for this mod and how you continue to improve it!

One thing I wanted to ask you about is if there's any chance you could adjust the response curves for the pitch and roll? Making them a bit less "aggressive".

I'm also using the mod linked below for the Bonanza G36 and one thing I really like about that mod/aircraft is how it has exactly this, less aggressive response curves for both pitch and roll. Making it feel more realistic and less "arcade'ish".

https://github.com/roblenvic/Bonanza-Turbo

Again, many thanks for your work on this aircraft and I love how we now can also open the doors 🙂

**Comment by mixMugz** [comment]
I can't realise that, because it's only subjectively. I don't have real TBM930 pilot, and not have real information about that
