### ISSUE TITLE
Assign the AP/Trim Disconnect button to a physical button on your yoke

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#10]
Not sure if/what is possible via a mod like this one but one thing that annoys me is how it's not possible to extinguish the AP Disconnect warning light on the FMA without pressing the AP/Trim Disconnect button on the yoke in the virtual cockpit. I would like being able to map that to a physical button on my own yoke.

I've already tried all AP Disconnect/OFF etc commands I could find in MSFS but they just disconnects the AP but leaves the red, visual warning blinking on the FMA on the PFD.

However as I started this post, I guess this is hard to fix in a mod but is rather something that needs to be fixed within MSFS itself, to add another command that has the same effect as pressing the AP/Trim Disconnect button on the virtual yoke.

**Comment by mixMugz** [comment]
This is simulator problem. I cant create command to use in Simulator

**Comment by WebMaximus** [comment]
That's what I thought.

Thanks anyway!
