### ISSUE TITLE
Enable/disable virtual pilots

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#11]
Really cool with the pilots seen not only in outside view but now also inside the cockpit!

Would be nice though to have a way to permanently decide if you want them visible or not without having to adjust the weight (smart idea though). Maybe via some simple ShowPilotsInCockpit = OFF/ON flag in a config file?

**Comment by Lysdestic** [comment]
I would personally love being able to set the copilot state and whether the door is open at spawn via a config file.

Just an idea to add to this, I know the Working Title guys use a method of storing their settings in the user save data, perhaps that same approach could be used here as well? A config file works just fine for me, though.

**Comment by mixMugz** [comment]
You can do it now by adding to .flt files [LocalVars.0] section.
XMLVAR_TBM930_HidePilot=1
XMLVAR_TBM930_HideCoPilot=1
Or you can remove it by default putting in PAYLOAD value less than 100lb.

**Comment by WebMaximus** [comment]
> You can do it now by adding to .flt files [LocalVars.0] section.
> XMLVAR_TBM930_HidePilot=1
> XMLVAR_TBM930_HideCoPilot=1
> Or you can remove it by default putting in PAYLOAD value less than 100lb.

Exactly what I was looking for! Many thanks, looking forward to try it out 🙂

**Comment by mixMugz** [comment]
If problem resolved - close issue

**Comment by Lysdestic** [comment]
Before this gets closed, instead of having the user edit the .flt files, would you consider adding a cfg file to the mod directory that the user can just specify true/false on which then sets those values? I think that would be a more elegant solution than editing stock files, personally.

**Comment by mixMugz** [comment]
> > Yes. Already added option to FLT files. In next release
> 
> Sounds great!
> 
> I've now tried modifying the .flt files and it worked perfectly but having a cfg file will be even better 👍

no no. No cfg files. Only FLT. I cant operate with CFG files. Maybe i create something for save state, but not now. 
in next release i add only configurable FLT option

**Comment by WebMaximus** [comment]
> > > Yes. Already added option to FLT files. In next release
> > 
> > 
> > Sounds great!
> > I've now tried modifying the .flt files and it worked perfectly but having a cfg file will be even better 👍
> 
> no no. No cfg files. Only FLT. I cant operate with CFG files. Maybe i create something for save state, but not now.
> in next release i add only configurable FLT option

Ah, sorry. I thought you said that in your comment above but whatever you do it will be fine I'm sure.

**Comment by subn3t** [comment]
I'm unable to remove the pilot & copilot models by any means.

The red display buttons on either side of the PFDs don't work
Setting the weight to 99lb for pilot/copilot doesn't work
Updating the .FLT files doesn't work

🤷‍♂️

**Comment by mixMugz** [comment]
> I'm unable to remove the pilot & copilot models by any means.
> 
> The red display buttons on either side of the PFDs don't work
> Setting the weight to 99lb for pilot/copilot doesn't work
> Updating the .FLT files doesn't work

Check your mods. Possible conflict.
