### ISSUE TITLE
Drag too high when dirty

### ISSUE THREAD

**Issue by rwilsonlj** [mixMugz/msfs_tbm930_project#15]
FYI, I noticed today that on an ILS approach nearing the runway with flaps full and gear extended that it took nearly full throttle to maintain 90 knots. I don't think this is correct.

**Comment by mixMugz** [comment]
Try new version. If all ok, close issue

**Comment by rwilsonlj** [comment]
Thanks for the update. The approach speeds/power are more accurate. Great mod!
