### ISSUE TITLE
Sometimes pitching violently up when selecting VS

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#17]
Mostly during approaches, I've seen how sometimes going from ALT to VS mode will make the aircraft pitch up very aggressively. When this happens, the easiest way to fix this seems to be deselecting VS mode and then reselect it.

This is still quite annoying where you risk busting an altitude restriction in matter of seconds if you're not very quick.

Not sure if this is an Asobo, a  TBM 930 project or even a WT issue?

**Comment by mixMugz** [comment]
autopilot problems are not mod related

**Comment by WebMaximus** [comment]
That's what I thought but thanks for confirming.
