### ISSUE TITLE
Door lock indicators

### ISSUE THREAD

**Issue by BostonClipper** [mixMugz/msfs_tbm930_project#2]
The TBM 930 PILOT'S INFORMATION MANUAL 7.3.9 (https://www.tbm.aero/wp-content/uploads/2016/03/PIM-930__AN__E0.pdf)
states "Check that all latch pins and hooks are correctly engaged (visible green marks).". How do I "lock" the doors so that the green marks display?

**Comment by mixMugz** [comment]
Changed in v0.5.9
- Green (locked)
- Red (Unlocked)

**Comment by paytonjk** [comment]
Great mod.  Adds a nice touch of realism.  I have just one issue and I'm not sure if it's user error or not.  The luggage compartment door kept opening as I accelerated for takeoff.  I did notice the Green/Red Lock Indicator for the passenger and pilot doors however, I didn't notice a Lock Indicator for the luggage door.  How can I verify that the luggage compartment door is locked prior to takeoff?  Thanks.

**Comment by mixMugz** [comment]
Door automatic close and lock at 30kt

**Comment by paytonjk** [comment]
Okay thanks.  I made a couple flights today and didn't have the problem.
Thanks for the reply.

**Comment by paytonjk** [comment]
Greetings.  I downloaded and installed your TBM mode however, since last
week's MSFS 2020 update, I am no longer able to find your mod in my list of
aircraft.  The file is still in my community folder.  What can I do to make
your mod visible in my aircraft livery?

Thanks.
