### ISSUE TITLE
Problems starting engine (most likely not mod related, just a question)

### ISSUE THREAD

**Issue by philhzss** [mixMugz/msfs_tbm930_project#20]
Hi mugz, thanks for this wonderful mod.

This is probably a MSFS2020 issue more than an issue with your mod, but do you know why when I go from ground idle to flight idle after starting, the engine quits? I have followed a ton of tutorials and I'm under the impression im doing everything right, but it doens't work. 

The only workarounds I've found are going full throttle on my joystick when on ground idle, which moves the in-game throttle to full power and then i can drag it down to flight idle and it doesn't stall. Or, drag the "man override" red lever slightly up before dragging the throttle from ground to flight idle, also works. 

This issue appeared a few months ago, I used to be able to start it fine. It happens with an without the mod, but I was wondering if this can be fixed by your mod? Or if you know what Im doing wrong, can you tell me?

If not feel free to close this!

Thanks

**Comment by Indianb0y016** [comment]
I had a similar issue recently too. Something to ensure is that you dont have any mixture or prop axis assigned. Those will override the power settings in most aircraft, I think. My issue once was when I had a prop axis assigned. The throttle refused to go to flight idle and wouldnt cut either. Removing that axis assignment solved the issue. Hope this helps!

**Comment by philhzss** [comment]
Thanks a lot!! I sadly do not have any mixture or prop axis, I only have flight controls + foot pedals for brakes. Although now that I think of it, I do have an Xbox controller also plugged in and I'm not sure what axis that has.... I'll take a look. I'll also try removing my joysticks throttle control, just to see if it helps. In the meantime, just moving my physical throttle (when the in-game one is still on ground idle) seems to work, at least. But thanks a lot for the idea!! I'll update this post after my findings

**Comment by mixMugz** [comment]
Can close the issue?

**Comment by ZeroL16** [comment]
Hey, so whenever I'm starting my engine I can't move the throttle over to flight idle, any fixes?

**Comment by mixMugz** [comment]
> Hey, so whenever I'm starting my engine I can't move the throttle over to flight idle, any fixes?

Read KNOWN ISSUE. It's SU5 addition. When you move throttle from Hi Iddle hold LM and press RM

**Comment by philhzss** [comment]
> Can close the issue?

Haven't flown the sim for ages so not sure, but if no one else complained it was probably an issue on my side so you can go ahead and close it, thanks!
