### ISSUE TITLE
With todays update V 1-18 I'm not able to see most of my plane. 

### ISSUE THREAD

**Issue by mahensley** [mixMugz/msfs_tbm930_project#23]
Are you working on an update for compatibility with the newest update? The stock plane is nothing like your mod so I'm very hopeful. Also can you advise about working title g-3000? I hope to be buying you some coffee if you can get me in the air again.
Thanks in advance Mugz!

**Comment by diaznet** [comment]
Same bug here, SU5 totally broke this mod. Moving away the mod directory fixes the issue, but sadly I am back with the stock plane which is not so great.

**Comment by JennyD73** [comment]
Sadly i believe this mod is now dead i really hope im proven wrong though

**Comment by mahensley** [comment]
Hey Mugz! Its not like you to not be responding so TBM aside I hope all is well with you...

**Comment by BradleyGother** [comment]
<img width="960" alt="tbm930" src="https://user-images.githubusercontent.com/81194288/127497988-845b7f8b-288d-4d30-9d78-a0fc9636ba30.png">

**Comment by BradleyGother** [comment]
TBM says no to SU5. Cleared cache & re-started with addon disabled & it works fine, tried again to enable and still getting no interior loading as in pic above?

**Comment by mixMugz** [comment]
The mod not compatible yet!

**Comment by WebMaximus** [comment]
> TBM says no to SU5. Cleared cache & re-started with addon disabled & it works fine, tried again to enable and still getting no interior loading as in pic above?

Have a friend having the same issue. Can you please elaborate on "cleared cache" if that is a required step to get the TBM working again?

**Comment by mahensley** [comment]
Good to hear from you! I feel much better knowing your on the job. 

Everyone should get some coffee money ready if they fly your TBM

**Comment by Indianb0y016** [comment]
The mod is not compatible with SU5. If you are unaware, Mugz had some technical difficulties with his sim for a while, which prevented him from working on his mods. I believe the issue was resolved, but by that time, SU5 was close to release so I THINK he decided to wait for it to be released to update the mod. Have patience my friends!

**Comment by mixMugz** [comment]
Fixed
