### ISSUE TITLE
LDG flap drag too high 

### ISSUE THREAD

**Issue by nAUTILUS249** [mixMugz/msfs_tbm930_project#24]
Love the mod, great work! Thanks for updating to SU5. There is one area where performance differs from the POH significantly though. Flaps in landing position add too much drag and result in very bad climb performance. The POH states about 1000-1500 fpm at 50% payload if I recall correctly while the FS version (vanilla as well as your mod) only gets around 150 at the most. 
About 50% torque is required to maintain a -500 fpm descent when in RL it should be about 20%. 
Could you edit the landing flap drag to fix this? 
Many thanks for reading and again, great mod so far!

**Comment by mixMugz** [comment]
Yes. I testing new drag coefficient.

**Comment by mixMugz** [comment]
Check new version, and if all ok, close the issue

**Comment by nAUTILUS249** [comment]
Much better, thank you! Well done
