### ISSUE TITLE
Problen with the screens

### ISSUE THREAD

**Issue by WAST3M4N1** [mixMugz/msfs_tbm930_project#25]
When the battery is off the middle one is black but the 2 side ones are purple when i turn the battery on they turn white and just stay like that
![tbm](https://user-images.githubusercontent.com/89041899/129620042-ce279312-76ef-46c7-8f07-62a80495cd04.JPG)
![tbm on](https://user-images.githubusercontent.com/89041899/129620053-d41356e9-005e-4235-9a28-d5bca543fddb.JPG)

**Comment by mixMugz** [comment]
Livery related problem.
1. Correct panel.cfg in livery
2. Remove panel.xml in livery
3. Rebuil layout.json

**Comment by WAST3M4N1** [comment]
how do i do that if u don't mind?

**Comment by mixMugz** [comment]
Send me your problem livery in discord i will fix it to you, if you cant

**Comment by WAST3M4N1** [comment]
the thing is not even the default one works

**Comment by WAST3M4N1** [comment]
i'll send you 2 liveries

**Comment by mixMugz** [comment]
Ok. One question. Do you have copilot mods? Remove it

**Comment by WAST3M4N1** [comment]
like all of them or just the one for the tbm? cuz i have them

**Comment by mixMugz** [comment]
> like all of them or just the one for the tbm? cuz i have them

For now remove all (standard), because it's not compatible with SU5. After update copilot mod you need remove copilot for TBA because copilots already have with this mod

**Comment by WAST3M4N1** [comment]
oh okay okay
then should i try to see if the screens work?

**Comment by mixMugz** [comment]
> then should i try to see if the screens work?

Yep

**Comment by WAST3M4N1** [comment]
oh it works

**Comment by WAST3M4N1** [comment]
tysm man

**Comment by WAST3M4N1** [comment]
cheers

**Comment by WAST3M4N1** [comment]
nevermind it still doesn't work

**Comment by WAST3M4N1** [comment]
the screens are now grey and white
the purple is gone

**Comment by mixMugz** [comment]
> the screens are now grey and white
> the purple is gone

With default livery?

**Comment by WAST3M4N1** [comment]
default livery works

**Comment by WAST3M4N1** [comment]
i sent you 2 liveries on discord if u can fix em

**Comment by mixMugz** [comment]
> i sent you 2 liveries on discord if u can fix em

When come to home

**Comment by WAST3M4N1** [comment]
ok man ty

**Comment by WAST3M4N1** [comment]
ok man can u fix the liveries now??
