### ISSUE TITLE
Baro Knob issue

### ISSUE THREAD

**Issue by DanP77** [mixMugz/msfs_tbm930_project#26]
"Push STD" does not work.
It could be nice to enable this function.

**Comment by mixMugz** [comment]
Work after FL180
It's by simulator design

**Comment by DanP77** [comment]
Is it possible to override that?
What I'm expecting is that the push knob function is always available, and generally used before crossing TA and TL.

**Comment by mixMugz** [comment]
Not sure, due it required rewrite G3000 mod. When WT g3000 realise STD switch function, then i can change know function
