### ISSUE TITLE
Door opens on take off 🔊 (KSAN), haven't tried other airports. Open Sound of Exterior no visual open door.

### ISSUE THREAD

**Issue by guccisoulja** [mixMugz/msfs_tbm930_project#27]
Door opens on take off 🔊 (KSAN), haven't tried other airports. 
- Open Sound of Exterior no visual open door.

**Comment by guccisoulja** [comment]
while using fseconomy, its working now. A++++

**Comment by mixMugz** [comment]
Closing issue?

**Comment by guccisoulja** [comment]
On take off the pax door would open at take-off happened 3 times could not
figure it out. I fixed it self. (Full throttle on take off - pax door
popping open no visuals

**Comment by guccisoulja** [comment]
13:30 Door Opens

https://youtu.be/Q1_HXG0darA

**Comment by mixMugz** [comment]
I have no idea. Did you using any external simconnect apps?

**Comment by guccisoulja** [comment]
No happened 3 Times - no issues since
