### ISSUE TITLE
Issue with the latest update

### ISSUE THREAD

**Issue by tbm900** [mixMugz/msfs_tbm930_project#32]
Hello, after the latest update today I have the problem that the Yokes are not able to get hide anymore. So there is no clickspot and you cant change the V/S ...You can activate it but cant choose a rate via the wheel...Thx for checking

**Comment by coleoptere91** [comment]
Temporary, remove TBM930 improvment and all will be Ok

**Comment by mixMugz** [comment]
Fixed with v0.6.2
