### ISSUE TITLE
Can't control wheel for vertical speed or flight level control with mouse. 

### ISSUE THREAD

**Issue by sh4d0wl3ss** [mixMugz/msfs_tbm930_project#35]

**Comment by fchosson** [comment]
same problem with vr or not, impossible to toggle off the yoke too

**Comment by Thatbitterlemon** [comment]
> 

Seems the Yoke issue is also happening with the Default MSFS TBM not just in this mod.

**Comment by spiff72** [comment]
Seeing the same issues here.  Has anyone confirmed whether the VS wheel works with the stock TBM930?  Hate to remove this mod but I want that VS wheel working!

**Comment by spiff72** [comment]
To answer my own question, deleting the mod and using the stock aircraft solved the VS wheel issue and the inability to hide the yoke.

**Comment by mixMugz** [comment]
Fixed in v0.6.2
