### ISSUE TITLE
Pink Lady Copilot

### ISSUE THREAD

**Issue by coleoptere91** [mixMugz/msfs_tbm930_project#39]
MSFS Deluxe Version
WT G3000 V0.7.6a
TBM930 Improvment last version

When switching to display my lady copilot  what a surprise yesterday  !!!
![TBM-Pink-Lady-Copilot](https://user-images.githubusercontent.com/82645975/145786143-7a601f01-170f-49b8-a712-3400a841da36.jpg)
e

**Comment by mixMugz** [comment]
It's not mod related. Pilots model is different. Check you pilots character mods.

**Comment by coleoptere91** [comment]
But I havn't other pilots mod 
In my Community only
WT G3000 V0.7.6a 
your TBM930 Improvment 0.6.2

**Comment by mixMugz** [comment]
I mean character mods may be? Try disable all mods instead TBM930 mod and check

**Comment by coleoptere91** [comment]
Will try and will be back soon

**Comment by coleoptere91** [comment]
No more problem if in MSFS Miscellaneous options iI select Pilot2 instead of Pilot10 as it was !
Thanks for help.
