### ISSUE TITLE
Subscribe to the releases page

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#43]
Not an issue but a question about github, is it somehow possible to subscribe to the releases page to get an email notification when a new version has been released?

This is the page I'm referring to

https://github.com/mixMugz/msfs_tbm930_project/releases

**Comment by mixMugz** [comment]
![image](https://user-images.githubusercontent.com/17923916/148641059-8ae9ec60-7767-4fce-bd5b-dac943517570.png)

Or use flightsim.to

**Comment by WebMaximus** [comment]
Thanks but where do you find the screen you're showing in that screenshot? The UI almost looks a bit like Discord to me. I'm using Chrome to go to your Github page.

No big deal though, noticed how you just released a new version 🙂

**Comment by mixMugz** [comment]
![image](https://user-images.githubusercontent.com/17923916/148679910-1cf76b75-3b54-4d84-a410-3bf5063b16d0.png)

**Comment by WebMaximus** [comment]
Ah, thanks!

Just found out why I didn't see that option. I was using my mobile and I had to use the option in Chrome saying the web page is made for computers. Doing that revealed the option you're showing.

**Comment by diaznet** [comment]
I use this tool to keep all my Github packages up to date: https://github.com/NicolasConstant/msfs-community-downloader
Beats the Github Watch IMHO.

**Comment by WebMaximus** [comment]
Thanks for the tip!
