### ISSUE TITLE
Using the cabin light switch causes MSFS to CTD

### ISSUE THREAD

**Issue by WebMaximus** [mixMugz/msfs_tbm930_project#7]
Probably not related to the this mod but still wanted to ask if someone in here using the mod has experienced the same issue?

I've seen this a couple of times now, where pressing the cabin light switch either to switch the light ON or OFF results in a short freeze for a second or so where also all sound stops. Right after this, I'm back on my desktop.

I'm doing all my flying in VR using a pair of HP Reverb G2 glasses. Not sure if that might be of relevance here. Looking in the Application log in Windows Event Viewer after these crashes, this is what I find

```
Faulting application name: FlightSimulator.exe, version: 0.0.0.0, time stamp: 0x6027b4a3
Faulting module name: PerceptionDevice.dll_unloaded, version: 10.0.19041.746, time stamp: 0x24cb77e5
Exception code: 0xc0000005
Fault offset: 0x0000000000012f0f
Faulting process id: 0x349c
Faulting application start time: 0x01d70adcaeba4336
Faulting application path: C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.13.16.0_x64__8wekyb3d8bbwe\FlightSimulator.exe
Faulting module path: PerceptionDevice.dll
Report Id: f2eb5f82-74fe-489a-99ef-1378c0b14fcb
Faulting package full name: Microsoft.FlightSimulator_1.13.16.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by ReZZeR13** [comment]
I dont use VR and the cabin light operates fine.

**Comment by mixMugz** [comment]
Issue still exist?

**Comment by WebMaximus** [comment]
Haven't seen it in a while so I think this can be closed.
